-- Hand-written (not generated by `prisma migrate dev`) because Prisma's
-- schema diffing can't see inside Unsupported("geometry(...)") columns —
-- it has no idea GIST is even an option, so it would never propose these
-- on its own. This file exists purely as a vehicle to run raw SQL through
-- Prisma's migration history, applied via `prisma migrate deploy` (which
-- skips the shadow-database diffing step `migrate dev` uses — the shadow
-- DB doesn't have the PostGIS extension enabled, so validating this
-- migration there would fail even though it's correct).
--
-- GIST (Generalized Search Tree) is the standard PostGIS index type for
-- geometry columns — a B-tree (Postgres's default index type) can't
-- support spatial operators like ST_Contains/ST_DWithin, since there's no
-- natural sort order for 2D shapes. Without these, every isochrone
-- lookup and POI/mission/activity spatial query in Phase 4 would fall
-- back to a full table scan.
CREATE INDEX stations_location_idx ON "Station" USING GIST (location);
CREATE INDEX isochrones_polygon_idx ON "Isochrone" USING GIST (polygon);
CREATE INDEX pois_location_idx ON "Poi" USING GIST (location);
CREATE INDEX mapid_missions_location_idx ON "MapidMission" USING GIST (location);
CREATE INDEX mapid_activities_location_idx ON "MapidActivity" USING GIST (location);
